In [ ]:
import numpy as np
import pandas as pd

from datetime import datetime
from sklearn.metrics import pairwise_distances

import warnings
warnings.filterwarnings("ignore")

from google.colab import files
util = files.upload()
transformed_model_data = files.upload()

Saving util.py to util.py

Saving transformed_model_data_t1.csv to transformed_model_data_t1.csv

In [ ]:
from util import *

In [ ]:
df = pd.read_csv("transformed_model_data_t1.csv")

# Popularity

In [ ]:
exp_df = pd.DataFrame(columns=["model", "hit", "map",
                               "ndcg", "repl", "n_val_c"])
cust_base = df["c_id"].unique()

TRAIN_SIZE = 0.8
N_VAL = 5

k = 20
for v in range(N_VAL):
    hitt = 0
    pret = 0
    ndct = 0
    random_selection = np.random.rand(len(cust_base)) <= TRAIN_SIZE
    val_cust = cust_base[~random_selection]
    train_data = df[~(df["c_id"].isin(val_cust))]
    val_data = df[df["c_id"].isin(val_cust)]
    ret = train_data["item_id"].value_counts().keys()[:k]
    customer_list = val_data["c_id"].unique()
    counter = len(customer_list)
    for i in range(counter):
        c = customer_list[i]
        all = val_data.loc[val_data["c_id"]==c, "item_id"].values
        rel = all[-1]
        bl = np.isin(ret, rel)*1
        pre = average_precision(bl)
        ndc = ndcg_k(bl, len(bl))
        h = np.max(bl)
        hitt += h
        pret += pre
        ndct += ndc
    hit, mapp, ndcg = hitt/counter, pret/counter, ndct/counter
    exp_df = exp_df.append({"model": "popularity",
                            "hit": hit,
                            "map": mapp,
                            "ndcg": ndcg,
                            "repl": v+1,
                            "n_val_c": counter}, ignore_index=True)
    print(v)

file = "".join(np.random.choice(["a", "b", "c", "d", "e", 0, 1, 2, 3, 4], 4))
exp_df.to_csv("results_" + file + ".csv", sep=";", index=False)

0
1
2
3
4

In [ ]:
exp_df

        model       hit       map      ndcg repl n_val_c
0  popularity  0.056173  0.020774  0.029737    1    4771
1  popularity  0.058066  0.026821  0.035633    2    4891
2  popularity  0.056077  0.023788  0.032431    3    4797
3  popularity  0.059427  0.022772  0.032665    4    4779
4  popularity  0.058736  0.025176  0.034022    5    4716

# Last-random

In [ ]:
exp_df = pd.DataFrame(columns=["model", "hit", "map",
                               "ndcg", "repl", "n_val_c"])
cust_base = df["c_id"].unique()

TRAIN_SIZE = 0.8
N_VAL = 5

k = 20
for v in range(N_VAL):
    hitt = 0
    pret = 0
    ndct = 0
    random_selection = np.random.rand(len(cust_base)) <= TRAIN_SIZE
    val_cust = cust_base[~random_selection]
    val_data = df[df["c_id"].isin(val_cust)]
    customer_list = val_data["c_id"].unique()
    counter = len(customer_list)
    for i in range(counter):
        c = customer_list[i]
        all = val_data.loc[val_data["c_id"]==c, "item_id"].values
        rel = all[-1]
        rest = all[:-1]
        re = list()
        [re.append(r) if not r in re else False for r in rest]
        if len(re) > k:
            ret = np.random.choice(re, k, replace=False)
        else:
            ret = list()
            while len(re)>0:
                ri = re.pop()
                if ri not in ret:
                    ret.append(ri)
        bl = np.isin(ret, rel)*1
        pre = average_precision(bl)
        ndc = ndcg_k(bl, len(bl))
        h = np.max(bl)
        hitt += h
        pret += pre
        ndct += ndc
    hit, mapp, ndcg = hitt/counter, pret/counter, ndct/counter
    exp_df = exp_df.append({"model": "last-random",
                            "hit": hit,
                            "map": mapp,
                            "ndcg": ndcg,
                            "repl": v+1,
                            "n_val_c": counter}, ignore_index=True)
    print(v)

file = "".join(np.random.choice(["a", "b", "c", "d", "e", 0, 1, 2, 3, 4], 4))
exp_df.to_csv("results_" + file + ".csv", sep=";", index=False)

0
1
2
3
4

In [ ]:
exp_df

         model       hit       map      ndcg repl n_val_c
0  last-random  0.197112  0.175833  0.187931    1    4779
1  last-random  0.206925  0.185939  0.199003    2    4765
2  last-random  0.202554  0.180395  0.194073    3    4621
3  last-random  0.197189  0.178093  0.189908    4    4767
4  last-random  0.199576  0.179292  0.191898    5    4715

# Last-ordered

In [ ]:
exp_df = pd.DataFrame(columns=["model", "hit", "map",
                               "ndcg", "repl", "n_val_c"])
cust_base = df["c_id"].unique()

TRAIN_SIZE = 0.8
N_VAL = 5

k = 20
for v in range(N_VAL):
    hitt = 0
    pret = 0
    ndct = 0
    random_selection = np.random.rand(len(cust_base)) <= TRAIN_SIZE
    val_cust = cust_base[~random_selection]
    val_data = df[df["c_id"].isin(val_cust)]
    customer_list = val_data["c_id"].unique()
    counter = len(customer_list)
    for i in range(counter):
        c = customer_list[i]
        all = val_data.loc[val_data["c_id"]==c, "item_id"].values
        rel = all[-1]
        rest = all[:-1]
        re = list()
        [re.append(r) if not r in re else False for r in rest]
        ret = re[-k:]
        bl = np.isin(ret, rel)*1
        pre = average_precision(bl)
        ndc = ndcg_k(bl, len(bl))
        h = np.max(bl)
        hitt += h
        pret += pre
        ndct += ndc
    hit, mapp, ndcg = hitt/counter, pret/counter, ndct/counter
    exp_df = exp_df.append({"model": "last-ordered",
                            "hit": hit,
                            "map": mapp,
                            "ndcg": ndcg,
                            "repl": v+1,
                            "n_val_c": counter}, ignore_index=True)
    print(v)

file = "".join(np.random.choice(["a", "b", "c", "d", "e", 0, 1, 2, 3, 4], 4))
exp_df.to_csv("results_" + file + ".csv", sep=";", index=False)

0
1
2
3
4

In [ ]:
exp_df

          model       hit       map      ndcg repl n_val_c
0  last-ordered  0.194979  0.146013  0.172323    1    4780
1  last-ordered  0.189633  0.141303  0.167477    2    4746
2  last-ordered  0.196912  0.144619  0.172196    3    4728
3  last-ordered  0.193137  0.141968  0.168142    4    4779
4  last-ordered  0.191186  0.138859  0.166807    5    4765

# User-similarity

In [ ]:
exp_df = pd.DataFrame(columns=["model", "n", "hit", "map",
                               "ndcg", "repl", "n_val_c"])
cust_base = df["c_id"].unique()

TRAIN_SIZE = 0.8
N_VAL = 1

ns = [150]
k = 20
for v in range(N_VAL):
    random_selection = np.random.rand(len(cust_base)) <= TRAIN_SIZE
    val_cust = cust_base[~random_selection]
    val_data = df[df["c_id"].isin(val_cust)]
    lasts = val_data.groupby("c_id", as_index=False).last()
    last_tr = lasts["t_id"].unique()
    train_data = df[~(df["t_id"].isin(last_tr))]
    user = pd.pivot_table(data=train_data,
                          values="payment",
                          index="c_id",
                          columns="item_id")
    user = user.apply(lambda x: x/x, axis=1)
    user = user.fillna(0)
    for n in ns:
        hitt = 0
        pret = 0
        ndct = 0
        customer_list = val_data["c_id"].unique()
        counter = len(customer_list)
        for i in range(counter):
            if (i%1000)==0:
                print(i)
            c = customer_list[i]
            all = val_data.loc[val_data["c_id"]==c, "item_id"].values
            rel = all[-1]
            score = 1 - pairwise_distances(user[user.index==c], user, metric="cosine")
            nn = user.index[score[0].argsort()[::-1][1:n+1]]
            rank_table = list()
            for h in nn: 
                rank_table.append(user[user.index==h].values)
            ranks = np.mean(rank_table, axis=0)[0].argsort()[::-1][:k]
            ret = list(user.columns[ranks])
            bl = np.isin(ret, rel)*1
            pre = average_precision(bl)
            ndc = ndcg_k(bl, len(bl))
            h = np.max(bl)
            hitt += h
            pret += pre
            ndct += ndc
        hit, mapp, ndcg = hitt/counter, pret/counter, ndct/counter
        exp_df = exp_df.append({"model": "user-similarity",
                                "n": n,
                                "hit": hit,
                                "map": mapp,
                                "ndcg": ndcg,
                                "repl": v+1,
                                "n_val_c": counter}, ignore_index=True)
    print(v)

file = "".join(np.random.choice(["a", "b", "c", "d", "e", 0, 1, 2, 3, 4], 4))
exp_df.to_csv("results_" + file + ".csv", sep=";", index=False)
files.download("results_" + file + ".csv")

0
1000
2000
3000
4000
0